FROM python:3.6

ADD ./requirements.txt /

RUN pip install -r requirements.txt

RUN apt-get update

RUN apt-get -y install ipython

RUN pip install jupyter

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--allow-root", "--notebook-dir=/data/"]